# Generated by Django 5.2.5 on 2025-08-17 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=3, null=True)),
                ('lang_code', models.CharField(default='en-US', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_text', models.TextField(blank=True, null=True)),
                ('agent_text', models.TextField(blank=True, null=True)),
                ('asr_confidence', models.FloatField(blank=True, null=True)),
                ('user_audio_ms', models.IntegerField(blank=True, null=True)),
                ('tts_ms', models.IntegerField(blank=True, null=True)),
                ('grammar_feedback', models.JSONField(blank=True, default=list)),
                ('pronunciation', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='aurora_sessions.practicesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clip_type', models.CharField(choices=[('user', 'user'), ('tts', 'tts')], max_length=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='sessions/audio/')),
                ('preview_b64', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(default='audio/ogg', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_clips', to='aurora_sessions.turn')),
            ],
        ),
    ]
